=== Shrikantgrh/osbproject/ResourceRepository/RaveSTS/Schemas/RaveODM.xsd
<xsd:schema targetNamespace="http://www.cdisc.org/ns/odm/v1.3" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.cdisc.org/ns/odm/v1.3" xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:xlink="http://www.w3.org/1999/xlink">
  <xsd:import schemaLocation="mdsol.xsd" namespace="http://www.mdsol.com/ns/odm/metadata"/>

    <xsd:element name="ODM" type="ODM"/>
    <xsd:complexType name="ODM">
        <xsd:sequence>
            <xsd:element name="ClinicalData" maxOccurs="unbounded" type="ClinicalData"/>
        </xsd:sequence>
        <xsd:attribute name="FileType" type="xsd:string"/>
        <xsd:attribute name="FileOID" type="xsd:string"/>
        <xsd:attribute name="CreationDateTime" type="xsd:string"/>
        <xsd:attribute name="ODMVersion" type="xsd:float"/>
    </xsd:complexType>
    <xsd:complexType name="ClinicalData">
        <xsd:sequence>
            <xsd:element name="SubjectData" type="SubjectData"/>
        </xsd:sequence>
        <xsd:attribute name="StudyOID" type="xsd:string"/>
        <xsd:attribute name="MetaDataVersionOID" type="xsd:integer"/>
    </xsd:complexType>
    <xsd:complexType name="SubjectData">
        <xsd:sequence>
            <xsd:element name="SiteRef" type="SiteRef"/>
            <xsd:element name="StudyEventData" type="StudyEventData"/>
        </xsd:sequence>
        <xsd:attribute name="SubjectKey" type="xsd:integer"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="SiteRef">
        <xsd:attribute name="LocationOID" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="StudyEventData">
        <xsd:sequence>
            <xsd:element name="FormData">
                <xsd:complexType>
                    <xsd:complexContent>
                        <xsd:extension base="FormData"/>
                    </xsd:complexContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="StudyEventOID" type="xsd:string"/>
        <xsd:attribute name="StudyEventRepeatKey" type="xsd:integer"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="FormData">
        <xsd:sequence>
            <xsd:element name="ItemGroupData" type="ItemGroupData"/>
        </xsd:sequence>
        <xsd:attribute name="FormOID" type="xsd:string"/>
        <xsd:attribute name="FormRepeatKey" type="xsd:integer"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="ItemGroupData">
        <xsd:sequence>
            <xsd:element name="ItemData" maxOccurs="unbounded" type="ItemData"/>
        </xsd:sequence>
        
        <xsd:attribute name="ItemGroupOID" type="xsd:string"/>
        <xsd:attribute name="ItemGroupRepeatKey" type="xsd:string"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="ItemData">
        <xsd:attribute name="ItemOID" type="xsd:string"/>
        <xsd:attribute name="Value" type="xsd:string"/>
        <xsd:attribute name="IsNull" type="xsd:string"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
         <xsd:attribute ref="mdsol:Lock"/>

    </xsd:complexType>
</xsd:schema>

=== Shrikantgrh/osbproject/ResourceRepository/RaveSTS/XSLT/XSLNonDeployedFiles/KAR-007_JustOneClinical_Transformation-Source.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<tns:ODM FileType="Transactional" FileOID="7b934e87-8669-4522-bfbb-11eeb2fa0751" CreationDateTime="2021-01-20T06:02:09.776-00:00" ODMVersion="1.3" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://soa.incresearch.com/Rave/URL" xmlns:java="http://www.oracle.com/XSL/Transform/java/java.lang.String" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:client="http://xmlns.oracle.com/RaveSTSPOC/DemoStudyTFM/DemoStudyBPELProcess" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:tns="http://www.cdisc.org/ns/odm/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cdisc.org/ns/odm/v1.3 file:/Users/shrek/jdeveloper/mywork/RaveSTSServiceBusApplication/ResourceRepository/RaveSTS/Schemas/RaveODM.xsd">
   <tns:ClinicalData MetaDataVersionOID="80" StudyOID="">
      <tns:SubjectData TransactionType="Update" SubjectKey="007-005-001">
         <tns:SiteRef LocationOID="targetLocationOID200"/>
         <tns:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <tns:FormData FormOID="DM" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="DM_LOG_LINE" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.AGE" Value="53" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.CBP" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.DOB" Value="28/FEB/1967" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.ETHNIC" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.RACE" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.RACESP" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.SEX" Value="M" TransactionType="Update"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
      </tns:SubjectData>
   </tns:ClinicalData>
   <tns:ClinicalData MetaDataVersionOID="80" StudyOID="">
      <tns:SubjectData TransactionType="Update" SubjectKey="007-005-001">
         <tns:SiteRef LocationOID="targetLocationOID200"/>
         <tns:StudyEventData StudyEventOID="SUBJECT" TransactionType="Update">
            <tns:FormData FormOID="EN" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="EN_LOG_LINE" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="EN.SUBJID" Value="007-005-001" TransactionType="Update"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
      </tns:SubjectData>
   </tns:ClinicalData>
   <tns:ClinicalData MetaDataVersionOID="80" StudyOID="">
      <tns:SubjectData TransactionType="Update" SubjectKey="007-005-001">
         <tns:SiteRef LocationOID="targetLocationOID200"/>
         <tns:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <tns:FormData FormOID="MH" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="MH_LOG_LINE" ItemGroupRepeatKey="1" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="MH.MHENDAT" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="MH.MHONG" Value="1" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="MH.MHSTDAT" Value="un/UNK/1988" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="MH.RECGUID" Value="Schizophrenia" TransactionType="Context"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
      </tns:SubjectData>
   </tns:ClinicalData>
   <tns:ClinicalData MetaDataVersionOID="80" StudyOID="">
      <tns:SubjectData TransactionType="Update" SubjectKey="007-005-001">
         <tns:SiteRef LocationOID="targetLocationOID200"/>
         <tns:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <tns:FormData FormOID="PE" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="PE_LOG_LINE" ItemGroupRepeatKey="1" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PE.BODYSYS" Value="1" TransactionType="Context"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PE.FINDING" Value="2" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PE.PEABNSP" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PE.PEDAT" Value="21/Dec/2020" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PE.PEREAS" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PE.PEYN" Value="Y" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PE.TEMP" Value="36.7" TransactionType="Update"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
      </tns:SubjectData>
   </tns:ClinicalData>
   <tns:ClinicalData MetaDataVersionOID="80" StudyOID="">
      <tns:SubjectData TransactionType="Update" SubjectKey="007-005-001">
         <tns:SiteRef LocationOID="targetLocationOID200"/>
         <tns:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <tns:FormData FormOID="VS" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="VS_LOG_LINE" ItemGroupRepeatKey="1" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="VS.HEIGHT" Value="190.5" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="VS.HEIGHTU" Value="1" TransactionType="Update"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
      </tns:SubjectData>
   </tns:ClinicalData>
   <tns:ClinicalData MetaDataVersionOID="80" StudyOID="">
      <tns:SubjectData TransactionType="Update" SubjectKey="007-005-001">
         <tns:SiteRef LocationOID="targetLocationOID200"/>
         <tns:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <tns:FormData FormOID="VS" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="VS_LOG_LINE" ItemGroupRepeatKey="2" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="VS.HEIGHT" Value="190.5" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="VS.HEIGHTU" Value="1" TransactionType="Update"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
      </tns:SubjectData>
   </tns:ClinicalData>
</tns:ODM>

=== Shrikantgrh/osbproject/ResourceRepository/RaveSTS/XSLT/XSLNonDeployedFiles/DRM06-AD05_Main_Transformation-Target.xml
<tns:ODM FileType="Transactional" FileOID="7bb0a590-b5ce-4f90-b659-5654bd00a213" CreationDateTime="2020-12-14T09:44:33.455-00:00" ODMVersion="1.3" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://soa.incresearch.com/Rave/URL" xmlns:java="http://www.oracle.com/XSL/Transform/java/java.lang.String" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:client="http://xmlns.oracle.com/RaveSTSPOC/DemoStudyTFM/DemoStudyBPELProcess" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:tns="http://www.cdisc.org/ns/odm/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cdisc.org/ns/odm/v1.3 file:/Users/shrek/jdeveloper/mywork/RaveSTSServiceBusApplication/ResourceRepository/RaveSTS/Schemas/RaveODM.xsd">
   <tns:ClinicalData MetaDataVersionOID="668" StudyOID="">
      <tns:SubjectData TransactionType="Update" SubjectKey="targetSubjectKey171">
         <tns:SiteRef LocationOID="targetLocationOID172"/>
         <tns:StudyEventData StudyEventOID="BASE" StudyEventRepeatKey="1" TransactionType="Update">
            <tns:FormData FormOID="PK" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="PK_LOG_LINE" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PK.PKDAT" Value="07/Dec/2021" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PK.PKND" Value="0" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="PK.PKTM" Value="10:23" TransactionType="Update"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
         <tns:StudyEventData StudyEventOID="BASE" StudyEventRepeatKey="1" TransactionType="Update">
            <tns:FormData FormOID="ADA" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="ADA_LOG_LINE" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="ADA.ADADAT" Value="07/Dec/2021" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="ADA.ADAND" Value="0" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="ADA.ADATM" Value="11:00" TransactionType="Update"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
      </tns:SubjectData>
   </tns:ClinicalData>
</tns:ODM>

=== Shrikantgrh/osbproject/ResourceRepository/RaveSTS/XSLT/XSLNonDeployedFiles/DRM06-AD06_Main_Transformation-Target.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<tns:ODM FileType="Transactional" FileOID="d54ee963-45a9-457d-b345-3f46e7e5eadc" CreationDateTime="2020-11-19T09:49:04.703-00:00" ODMVersion="1.3" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://soa.incresearch.com/Rave/URL" xmlns:java="http://www.oracle.com/XSL/Transform/java/java.lang.String" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:client="http://xmlns.oracle.com/RaveSTSPOC/DemoStudyTFM/DemoStudyBPELProcess" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:tns="http://www.cdisc.org/ns/odm/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cdisc.org/ns/odm/v1.3 file:/Users/shrek/jdeveloper/mywork/RaveSTSServiceBusApplication/ResourceRepository/RaveSTS/Schemas/RaveODM.xsd">
   <tns:ClinicalData MetaDataVersionOID="437" StudyOID="">
      <tns:SubjectData TransactionType="Update" SubjectKey="6014-003">
         <tns:SiteRef LocationOID="targetLocationOID99"/>
         <tns:StudyEventData StudyEventOID="AE" StudyEventRepeatKey="1" TransactionType="Update">
            <tns:FormData FormOID="AE" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="AE_LOG_LINE" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEYN" Value="N" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AETERM" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AESI" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEISA" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AESTDAT" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEONGO" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AESPDAT" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AESER" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AECN" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AESD" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEDTH" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEIPH" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AELTH" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEOTH" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEDTHDAT" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AESEV" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEREL" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEACT" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AENONE" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AECNMD" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEPROC" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEWTH" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEOTH1" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.OTHSP" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.AEOUT" IsNull="Yes" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="AE.RECGUID" Value="eb854678-7708-422a-8e04-eadc13a689f5" TransactionType="Context"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
      </tns:SubjectData>
   </tns:ClinicalData>
</tns:ODM>

=== Shrikantgrh/osbproject/ResourceRepository/RaveSTS/XSLT/XSLNonDeployedFiles/KAR-007_JustOneClinical_Transformation-Target.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<ns0:ODM xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ns0="http://www.cdisc.org/ns/odm/v1.3" FileType="Transactional" FileOID="7b934e87-8669-4522-bfbb-11eeb2fa0751" CreationDateTime="2021-01-20T06:02:09.776-00:00" ODMVersion="1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cdisc.org/ns/odm/v1.3 file:/Users/shrek/jdeveloper/mywork/RaveSTSServiceBusApplication/ResourceRepository/RaveSTS/Schemas/RaveODM.xsd">
   <ns0:ClinicalData StudyOID="" MetaDataVersionOID="80">
      <ns0:SubjectData SubjectKey="007-005-001" TransactionType="Update">
         <ns0:SiteRef LocationOID="targetLocationOID200"/>
         <ns0:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <ns0:FormData FormOID="DM" FormRepeatKey="1" TransactionType="Update">
               <ns0:ItemGroupData ItemGroupOID="DM_LOG_LINE" TransactionType="Update">
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="DM.AGE" Value="53" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="DM.CBP" IsNull="Yes" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="DM.DOB" Value="28/FEB/1967" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="DM.ETHNIC" IsNull="Yes" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="DM.RACE" IsNull="Yes" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="DM.RACESP" IsNull="Yes" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="DM.SEX" Value="M" TransactionType="Update"/>
               </ns0:ItemGroupData>
            </ns0:FormData>
         </ns0:StudyEventData>
         <ns0:StudyEventData StudyEventOID="SUBJECT" TransactionType="Update">
            <ns0:FormData FormOID="EN" FormRepeatKey="1" TransactionType="Update">
               <ns0:ItemGroupData ItemGroupOID="EN_LOG_LINE" TransactionType="Update">
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="EN.SUBJID" Value="007-005-001" TransactionType="Update"/>
               </ns0:ItemGroupData>
            </ns0:FormData>
         </ns0:StudyEventData>
         <ns0:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <ns0:FormData FormOID="MH" FormRepeatKey="1" TransactionType="Update">
               <ns0:ItemGroupData ItemGroupOID="MH_LOG_LINE" ItemGroupRepeatKey="@CONTEXT" TransactionType="Upsert">
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="MH.MHENDAT" IsNull="Yes" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="MH.MHONG" Value="1" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="MH.MHSTDAT" Value="un/UNK/1988" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="MH.RECGUID" Value="Schizophrenia" TransactionType="Context"/>
               </ns0:ItemGroupData>
            </ns0:FormData>
         </ns0:StudyEventData>
         <ns0:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <ns0:FormData FormOID="PE" FormRepeatKey="1" TransactionType="Update">
               <ns0:ItemGroupData ItemGroupOID="PE_LOG_LINE" ItemGroupRepeatKey="@CONTEXT" TransactionType="Upsert">
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PE.BODYSYS" Value="1" TransactionType="Context"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PE.FINDING" Value="2" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PE.PEABNSP" IsNull="Yes" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PE.PEDAT" Value="21/Dec/2020" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PE.PEREAS" IsNull="Yes" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PE.PEYN" Value="Y" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PE.TEMP" Value="36.7" TransactionType="Update"/>
               </ns0:ItemGroupData>
            </ns0:FormData>
         </ns0:StudyEventData>
         <ns0:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <ns0:FormData FormOID="VS" FormRepeatKey="1" TransactionType="Update">
               <ns0:ItemGroupData ItemGroupOID="VS_LOG_LINE" ItemGroupRepeatKey="1" TransactionType="Update">
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="VS.HEIGHT" Value="190.5" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="VS.HEIGHTU" Value="1" TransactionType="Update"/>
               </ns0:ItemGroupData>
            </ns0:FormData>
         </ns0:StudyEventData>
         <ns0:StudyEventData StudyEventOID="V0" StudyEventRepeatKey="1" TransactionType="Update">
            <ns0:FormData FormOID="VS" FormRepeatKey="1" TransactionType="Update">
               <ns0:ItemGroupData ItemGroupOID="VS_LOG_LINE" ItemGroupRepeatKey="2" TransactionType="Update">
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="VS.HEIGHT" Value="190.5" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="VS.HEIGHTU" Value="1" TransactionType="Update"/>
               </ns0:ItemGroupData>
            </ns0:FormData>
         </ns0:StudyEventData>
      </ns0:SubjectData>
   </ns0:ClinicalData>
</ns0:ODM>
