=== Shrikantgrh/osbproject/ResourceRepository/RaveSTS/Schemas/RaveODM.xsd
<xsd:schema targetNamespace="http://www.cdisc.org/ns/odm/v1.3" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.cdisc.org/ns/odm/v1.3" xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:xlink="http://www.w3.org/1999/xlink">
  <xsd:import schemaLocation="mdsol.xsd" namespace="http://www.mdsol.com/ns/odm/metadata"/>

    <xsd:element name="ODM" type="ODM"/>
    <xsd:complexType name="ODM">
        <xsd:sequence>
            <xsd:element name="ClinicalData" maxOccurs="unbounded" type="ClinicalData"/>
        </xsd:sequence>
        <xsd:attribute name="FileType" type="xsd:string"/>
        <xsd:attribute name="FileOID" type="xsd:string"/>
        <xsd:attribute name="CreationDateTime" type="xsd:string"/>
        <xsd:attribute name="ODMVersion" type="xsd:float"/>
    </xsd:complexType>
    <xsd:complexType name="ClinicalData">
        <xsd:sequence>
            <xsd:element name="SubjectData" type="SubjectData"/>
        </xsd:sequence>
        <xsd:attribute name="StudyOID" type="xsd:string"/>
        <xsd:attribute name="MetaDataVersionOID" type="xsd:integer"/>
    </xsd:complexType>
    <xsd:complexType name="SubjectData">
        <xsd:sequence>
            <xsd:element name="SiteRef" type="SiteRef"/>
            <xsd:element name="StudyEventData" type="StudyEventData"/>
        </xsd:sequence>
        <xsd:attribute name="SubjectKey" type="xsd:integer"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="SiteRef">
        <xsd:attribute name="LocationOID" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="StudyEventData">
        <xsd:sequence>
            <xsd:element name="FormData">
                <xsd:complexType>
                    <xsd:complexContent>
                        <xsd:extension base="FormData"/>
                    </xsd:complexContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="StudyEventOID" type="xsd:string"/>
        <xsd:attribute name="StudyEventRepeatKey" type="xsd:integer"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="FormData">
        <xsd:sequence>
            <xsd:element name="ItemGroupData" type="ItemGroupData"/>
        </xsd:sequence>
        <xsd:attribute name="FormOID" type="xsd:string"/>
        <xsd:attribute name="FormRepeatKey" type="xsd:integer"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="ItemGroupData">
        <xsd:sequence>
            <xsd:element name="ItemData" maxOccurs="unbounded" type="ItemData"/>
        </xsd:sequence>
        
        <xsd:attribute name="ItemGroupOID" type="xsd:string"/>
        <xsd:attribute name="ItemGroupRepeatKey" type="xsd:string"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="ItemData">
        <xsd:attribute name="ItemOID" type="xsd:string"/>
        <xsd:attribute name="Value" type="xsd:string"/>
        <xsd:attribute name="IsNull" type="xsd:string"/>
        <xsd:attribute name="TransactionType" type="xsd:string"/>
         <xsd:attribute ref="mdsol:Lock"/>

    </xsd:complexType>
</xsd:schema>

=== Shrikantgrh/osbproject/ResourceRepository/RaveSTS/XSLT/XSLNonDeployedFiles/DRM06-AD05_JustOneClinical_Transformation-Target.xml
<ns0:ODM xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ns0="http://www.cdisc.org/ns/odm/v1.3" FileType="Transactional" FileOID="7bb0a590-b5ce-4f90-b659-5654bd00a213" CreationDateTime="2020-12-14T09:44:33.455-00:00" ODMVersion="1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cdisc.org/ns/odm/v1.3 file:/Users/shrek/jdeveloper/mywork/RaveSTSServiceBusApplication/ResourceRepository/RaveSTS/Schemas/RaveODM.xsd">
   <ns0:ClinicalData StudyOID="" MetaDataVersionOID="668">
      <ns0:SubjectData SubjectKey="targetSubjectKey171" TransactionType="Update">
         <ns0:SiteRef LocationOID="targetLocationOID172"/>
         <ns0:StudyEventData StudyEventOID="BASE" StudyEventRepeatKey="1" TransactionType="Update">
            <ns0:FormData FormOID="PK" FormRepeatKey="1" TransactionType="Update">
               <ns0:ItemGroupData ItemGroupOID="PK_LOG_LINE" TransactionType="Update">
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PK.PKDAT" Value="07/Dec/2021" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PK.PKND" Value="0" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="PK.PKTM" Value="10:23" TransactionType="Update"/>
               </ns0:ItemGroupData>
            </ns0:FormData>
         </ns0:StudyEventData>
         <ns0:StudyEventData StudyEventOID="BASE" StudyEventRepeatKey="1" TransactionType="Update">
            <ns0:FormData FormOID="ADA" FormRepeatKey="1" TransactionType="Update">
               <ns0:ItemGroupData ItemGroupOID="ADA_LOG_LINE" TransactionType="Update">
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="ADA.ADADAT" Value="07/Dec/2021" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="ADA.ADAND" Value="0" TransactionType="Update"/>
                  <ns0:ItemData mdsol:Lock="AsFound" ItemOID="ADA.ADATM" Value="11:00" TransactionType="Update"/>
               </ns0:ItemGroupData>
            </ns0:FormData>
         </ns0:StudyEventData>
      </ns0:SubjectData>
   </ns0:ClinicalData>
</ns0:ODM>

=== Shrikantgrh/osbproject/ResourceRepository/RaveSTS/XSLT/XSLNonDeployedFiles/DRM06-AD04_Main_Transformation-Target.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<tns:ODM FileType="Transactional" FileOID="7da82858-c3fe-4fa8-9c9e-695a0c247190" CreationDateTime="2020-11-17T10:35:54.040-00:00" ODMVersion="1.3" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns1="http://soa.incresearch.com/Rave/URL" xmlns:java="http://www.oracle.com/XSL/Transform/java/java.lang.String" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:client="http://xmlns.oracle.com/RaveSTSPOC/DemoStudyTFM/DemoStudyBPELProcess" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:tns="http://www.cdisc.org/ns/odm/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cdisc.org/ns/odm/v1.3 file:/Users/shrek/jdeveloper/mywork/RaveSTSServiceBusApplication/ResourceRepository/RaveSTS/Schemas/RaveODM.xsd">
   <tns:ClinicalData MetaDataVersionOID="705" StudyOID="DRM06-AD07-KGAA(SDTSUAT)">
      <tns:SubjectData TransactionType="Update" SubjectKey="8805-880507">
         <tns:SiteRef LocationOID="8805"/>
         <tns:StudyEventData StudyEventOID="BASE" StudyEventRepeatKey="1" TransactionType="Update">
            <tns:FormData FormOID="DM" FormRepeatKey="1" TransactionType="Update">
               <tns:ItemGroupData ItemGroupOID="DM_LOG_LINE" TransactionType="Update">
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.BRTHDAT" Value="Jul/2003" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.SEX" Value="F" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.AGEY" Value="17" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.AGEG" Value="1" TransactionType="Update"/>
                  <tns:ItemData mdsol:Lock="AsFound" ItemOID="DM.BIRTHY" IsNull="Yes" TransactionType="Update"/>
               </tns:ItemGroupData>
            </tns:FormData>
         </tns:StudyEventData>
      </tns:SubjectData>
   </tns:ClinicalData>
</tns:ODM>
